# Generated by Django 4.2.10 on 2024-02-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="artwork",
            field=models.FileField(blank=True, upload_to="artworks/"),
        ),
    ]
