# Generated by Django 4.2.10 on 2024-02-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_story_artwork"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story", options={"verbose_name_plural": "Stories"},
        ),
        migrations.AddField(
            model_name="story",
            name="approved",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="story",
            name="author",
            field=models.CharField(default="", max_length=100),
        ),
    ]
